### ISSUE TITLE
פורום לעזרה

### ISSUE THREAD

**Issue by orielhaim** [shayaulman/kosher-code#117]
למה שלא ניצור פורום חרדי באתר שיעזור לאנשים בזמן הלמידה וגם מעבר.
(אוכל לעזור בכך בשמחה.)

**Comment by ynigun** [comment]
@orielhaim 
יש כבר פורומים כמו תחומים וכדו'
החסרון בפורום זה שאנשים מתביישים להציק עם שאלות 
למתחילים נראה לי שסלאק יותר יעיל.
יש לנו קהילה קטנה בסלאק אבל @shayaulman למשל לא רוצה להצטרף כי יש מידי הרבה הודעות
וזה עוד בקהילה קטנה של 46 חברים.
בקהילות ענקיות זה יכול להציק עוד יותר.
מה הפתרון? כנראה וגם סלאק וכל אחת יענה\ישאל איפה שמתאים לו.

**Comment by shayaulman** [comment]
אני גם חושב שאין טעם לפתוח עוד פורום כשיש כבר אינפלציה של פורומים (שחלק מהם באמת טובים).

לגבי הסלאק, אשמח להצטרף, שלח הזמנה...

**Comment by orielhaim** [comment]
מעניין מעולם לא הכרתי את סלאק...
בנוסף כל הפורומים שבציבור החרדי עובדים על אותה מערכת למי ששם לב... אני מתכוון ליצור מערכת חדשה (ונורמלית)

**Comment by yisrael-rosen** [comment]
@orielhaim 
רוב הפורומים מבוססים על phpBB או nodeBB
כי הם בקוד פתוח וקלים להתקנה.
אין הגיון לכתוב הכל מחדש כשבסופו של דבר זה יראה דומה לפורומים האחרים.

**Comment by yisrael-rosen** [comment]
@orielhaim
רוב הפורומים מבוססים על phpBB או nodeBB
כי הם בקוד פתוח וקלים להתקנה.
אין הגיון לכתוב הכל מחדש כשבסופו של דבר זה יראה דומה לפורומים האחרים.
