### ISSUE TITLE
learnxinyminutes.com

### ISSUE THREAD

**Issue by ynigun** [shayaulman/kosher-code#41]
חשבתי להוסיף את האתר 
https://learnxinyminutes.com/
לחומרי למידה.
?אני לא יודע איך לתייג את זה
?אני יעבור ויסנן את המדריכים המוצלחים
לבנתיים עברתי על המדריכים של 
GO JS Python Lua 
ונהנתי מאוד מהגישה

**Comment by shayaulman** [comment]
(לכה"פ לקבל טעימה ראשונה) אכן, נראה מוצלח מאוד
בדיוק ראיתי את זה לפני כמה ימים והתכוונתי להוסיף את זה לרשימה :)
אני חושב שאפשר לתייג תחת "מדריכים"
רעיון אחר?

**Comment by ynigun** [comment]
השאלה היא מי יראה את זה?
אם מישהו מחפש ללמוד lua
הוא יבחר בתגית lua ולא בתגית מדריכים.
